/**
 * The fonts the office can choose for a poster's name and designation.
 * GENERATED by scripts/fetch-poster-fonts.mjs — edit that list, then re-run it.
 *
 * Plain data, no DOM: the panel, the renderer and the server (which only lets
 * these ids into a published poster) all read it.
 *
 * Each face is registered under its own family name ("THK …") so that it can
 * never collide with the website's own @font-face rules, and with every weight
 * mapped onto the one file, so the browser never fakes a bold of a face that
 * is already heavy.
 */

/** Anek Telugu: the default, declared by the site's own stylesheet. */
export const DEFAULT_TELUGU = 'anek'

export const POSTER_FONTS = [
  {
    id: "anek",
    script: "te",
    label: "Anek Telugu",
    note: "The default poster type",
    family: "Anek Telugu",
    weight: 800,
    files: []
  },
  {
    id: "noto-sans",
    script: "te",
    label: "Noto Sans Telugu",
    note: "Plain and very legible",
    family: "THK Noto Sans Telugu",
    weight: 800,
    files: [
      {
        src: "/fonts/poster/noto-sans-telugu.woff2",
        range: "U+0951-0952, U+0964-0965, U+0C00-0C7F, U+1CDA, U+1CF2, U+200C-200D, U+25CC"
      },
      {
        src: "/fonts/poster/noto-sans-latin.woff2",
        range: "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD"
      }
    ]
  },
  {
    id: "ramabhadra",
    script: "te",
    label: "Ramabhadra",
    note: "Heavy headline type",
    family: "THK Ramabhadra",
    weight: 400,
    files: [
      {
        src: "/fonts/poster/ramabhadra-telugu.woff2",
        range: "U+0951-0952, U+0964-0965, U+0C00-0C7F, U+1CDA, U+1CF2, U+200C-200D, U+25CC"
      },
      {
        src: "/fonts/poster/ramabhadra-latin.woff2",
        range: "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD"
      }
    ]
  },
  {
    id: "ntr",
    script: "te",
    label: "NTR",
    note: "Bold, rounded display",
    family: "THK NTR",
    weight: 400,
    files: [
      {
        src: "/fonts/poster/ntr-telugu.woff2",
        range: "U+0951-0952, U+0964-0965, U+0C00-0C7F, U+1CDA, U+1CF2, U+200C-200D, U+25CC"
      },
      {
        src: "/fonts/poster/ntr-latin.woff2",
        range: "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD"
      }
    ]
  },
  {
    id: "baloo",
    script: "te",
    label: "Baloo Tammudu",
    note: "Friendly and heavy",
    family: "THK Baloo Tammudu",
    weight: 800,
    files: [
      {
        src: "/fonts/poster/baloo-telugu.woff2",
        range: "U+0951-0952, U+0964-0965, U+0C00-0C7F, U+1CDA, U+1CF2, U+200C-200D, U+25CC"
      },
      {
        src: "/fonts/poster/baloo-latin.woff2",
        range: "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD"
      }
    ]
  },
  {
    id: "hind-guntur",
    script: "te",
    label: "Hind Guntur",
    note: "Clean, modern",
    family: "THK Hind Guntur",
    weight: 700,
    files: [
      {
        src: "/fonts/poster/hind-guntur-telugu.woff2",
        range: "U+0951-0952, U+0964-0965, U+0C00-0C7F, U+1CDA, U+1CF2, U+200C-200D, U+25CC"
      },
      {
        src: "/fonts/poster/hind-guntur-latin.woff2",
        range: "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD"
      }
    ]
  },
  {
    id: "noto-serif",
    script: "te",
    label: "Noto Serif Telugu",
    note: "Formal, with serifs",
    family: "THK Noto Serif Telugu",
    weight: 800,
    files: [
      {
        src: "/fonts/poster/noto-serif-telugu.woff2",
        range: "U+0951-0952, U+0964-0965, U+0C00-0C7F, U+1CDA, U+1CF2, U+200C-200D, U+25CC"
      },
      {
        src: "/fonts/poster/noto-serif-latin.woff2",
        range: "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD"
      }
    ]
  },
  {
    id: "suranna",
    script: "te",
    label: "Suranna",
    note: "Traditional book type",
    family: "THK Suranna",
    weight: 400,
    files: [
      {
        src: "/fonts/poster/suranna-telugu.woff2",
        range: "U+0951-0952, U+0964-0965, U+0C00-0C7F, U+1CDA, U+1CF2, U+200C-200D, U+25CC"
      },
      {
        src: "/fonts/poster/suranna-latin.woff2",
        range: "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD"
      }
    ]
  },
  {
    id: "tiro",
    script: "te",
    label: "Tiro Telugu",
    note: "Classic print",
    family: "THK Tiro Telugu",
    weight: 400,
    files: [
      {
        src: "/fonts/poster/tiro-telugu.woff2",
        range: "U+0951-0952, U+0964-0965, U+0C00-0C7F, U+1CDA, U+1CF2, U+200C-200D, U+25CC"
      },
      {
        src: "/fonts/poster/tiro-latin.woff2",
        range: "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD"
      }
    ]
  },
  {
    id: "mandali",
    script: "te",
    label: "Mandali",
    note: "Soft and open",
    family: "THK Mandali",
    weight: 400,
    files: [
      {
        src: "/fonts/poster/mandali-telugu.woff2",
        range: "U+0951-0952, U+0964-0965, U+0C00-0C7F, U+1CDA, U+1CF2, U+200C-200D, U+25CC"
      },
      {
        src: "/fonts/poster/mandali-latin.woff2",
        range: "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD"
      }
    ]
  },
  {
    id: "sree-krushnadevaraya",
    script: "te",
    label: "Sree Krushnadevaraya",
    note: "Calligraphic",
    family: "THK Sree Krushnadevaraya",
    weight: 400,
    files: [
      {
        src: "/fonts/poster/sree-krushnadevaraya-telugu.woff2",
        range: "U+0951-0952, U+0964-0965, U+0C00-0C7F, U+1CDA, U+1CF2, U+200C-200D, U+25CC"
      },
      {
        src: "/fonts/poster/sree-krushnadevaraya-latin.woff2",
        range: "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD"
      }
    ]
  },
  {
    id: "timmana",
    script: "te",
    label: "Timmana",
    note: "Playful hand-drawn",
    family: "THK Timmana",
    weight: 400,
    files: [
      {
        src: "/fonts/poster/timmana-telugu.woff2",
        range: "U+0951-0952, U+0964-0965, U+0C00-0C7F, U+1CDA, U+1CF2, U+200C-200D, U+25CC"
      },
      {
        src: "/fonts/poster/timmana-latin.woff2",
        range: "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD"
      }
    ]
  },
  {
    id: "dhurjati",
    script: "te",
    label: "Dhurjati",
    note: "Tall and narrow",
    family: "THK Dhurjati",
    weight: 400,
    files: [
      {
        src: "/fonts/poster/dhurjati-telugu.woff2",
        range: "U+0951-0952, U+0964-0965, U+0C00-0C7F, U+1CDA, U+1CF2, U+200C-200D, U+25CC"
      },
      {
        src: "/fonts/poster/dhurjati-latin.woff2",
        range: "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD"
      }
    ]
  },
  {
    id: "gidugu",
    script: "te",
    label: "Gidugu",
    note: "Light, airy",
    family: "THK Gidugu",
    weight: 400,
    files: [
      {
        src: "/fonts/poster/gidugu-telugu.woff2",
        range: "U+0951-0952, U+0964-0965, U+0C00-0C7F, U+1CDA, U+1CF2, U+200C-200D, U+25CC"
      },
      {
        src: "/fonts/poster/gidugu-latin.woff2",
        range: "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD"
      }
    ]
  },
  {
    id: "ponnala",
    script: "te",
    label: "Ponnala",
    note: "Elegant and light",
    family: "THK Ponnala",
    weight: 400,
    files: [
      {
        src: "/fonts/poster/ponnala-telugu.woff2",
        range: "U+0951-0952, U+0964-0965, U+0C00-0C7F, U+1CDA, U+1CF2, U+200C-200D, U+25CC"
      },
      {
        src: "/fonts/poster/ponnala-latin.woff2",
        range: "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD"
      }
    ]
  },
  {
    id: "akaya",
    script: "te",
    label: "Akaya Telivigala",
    note: "Decorative",
    family: "THK Akaya Telivigala",
    weight: 400,
    files: [
      {
        src: "/fonts/poster/akaya-telugu.woff2",
        range: "U+0951-0952, U+0964-0965, U+0C00-0C7F, U+1CDA, U+1CF2, U+200C-200D, U+25CC"
      },
      {
        src: "/fonts/poster/akaya-latin.woff2",
        range: "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD"
      }
    ]
  },
  {
    id: "poppins",
    script: "en",
    label: "Poppins",
    note: "Geometric, very bold",
    family: "THK Poppins",
    weight: 800,
    files: [
      {
        src: "/fonts/poster/poppins-latin.woff2",
        range: "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD"
      }
    ]
  },
  {
    id: "montserrat",
    script: "en",
    label: "Montserrat",
    note: "Wide and strong",
    family: "THK Montserrat",
    weight: 800,
    files: [
      {
        src: "/fonts/poster/montserrat-latin.woff2",
        range: "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD"
      }
    ]
  },
  {
    id: "oswald",
    script: "en",
    label: "Oswald",
    note: "Condensed headline",
    family: "THK Oswald",
    weight: 700,
    files: [
      {
        src: "/fonts/poster/oswald-latin.woff2",
        range: "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD"
      }
    ]
  },
  {
    id: "bebas",
    script: "en",
    label: "Bebas Neue",
    note: "Tall capitals",
    family: "THK Bebas Neue",
    weight: 400,
    files: [
      {
        src: "/fonts/poster/bebas-latin.woff2",
        range: "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD"
      }
    ]
  },
  {
    id: "anton",
    script: "en",
    label: "Anton",
    note: "Heavy condensed",
    family: "THK Anton",
    weight: 400,
    files: [
      {
        src: "/fonts/poster/anton-latin.woff2",
        range: "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD"
      }
    ]
  },
  {
    id: "archivo-black",
    script: "en",
    label: "Archivo Black",
    note: "Blocky and loud",
    family: "THK Archivo Black",
    weight: 400,
    files: [
      {
        src: "/fonts/poster/archivo-black-latin.woff2",
        range: "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD"
      }
    ]
  },
  {
    id: "raleway",
    script: "en",
    label: "Raleway",
    note: "Elegant sans",
    family: "THK Raleway",
    weight: 800,
    files: [
      {
        src: "/fonts/poster/raleway-latin.woff2",
        range: "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD"
      }
    ]
  },
  {
    id: "playfair",
    script: "en",
    label: "Playfair Display",
    note: "Classic serif (the website’s headings)",
    family: "THK Playfair Display",
    weight: 800,
    files: [
      {
        src: "/fonts/poster/playfair-latin.woff2",
        range: "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD"
      }
    ]
  },
  {
    id: "merriweather",
    script: "en",
    label: "Merriweather",
    note: "Sturdy serif",
    family: "THK Merriweather",
    weight: 900,
    files: [
      {
        src: "/fonts/poster/merriweather-latin.woff2",
        range: "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD"
      }
    ]
  },
  {
    id: "roboto-slab",
    script: "en",
    label: "Roboto Slab",
    note: "Slab serif",
    family: "THK Roboto Slab",
    weight: 800,
    files: [
      {
        src: "/fonts/poster/roboto-slab-latin.woff2",
        range: "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD"
      }
    ]
  },
  {
    id: "lora",
    script: "en",
    label: "Lora",
    note: "Book serif",
    family: "THK Lora",
    weight: 700,
    files: [
      {
        src: "/fonts/poster/lora-latin.woff2",
        range: "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD"
      }
    ]
  }
]

export const TELUGU_FONTS = POSTER_FONTS.filter((f) => f.script === 'te')
export const ENGLISH_FONTS = POSTER_FONTS.filter((f) => f.script === 'en')
export const fontById = (id) => POSTER_FONTS.find((f) => f.id === id) || null
