"""
Vendors the webfonts into public/fonts/ and writes their @font-face CSS.

WHY THIS EXISTS
The site used to pull fonts from Google's CDN with the standard
"load it as print, then flip it to all" trick:

    <link rel="stylesheet" href="https://fonts.googleapis.com/…"
          media="print" onload="this.media='all'">

That `onload` is an inline event handler, and the production CSP is
`script-src 'self'` with no 'unsafe-inline'. Chrome blocked the handler, the
stylesheet stayed at media="print", and every webfont on the site silently
fell back — Playfair Display rendered as Georgia and Inter as system-ui. It
only showed up in production because localhost never applies vercel.json's
headers.

Self-hosting fixes the cause rather than the symptom:
  - no inline handler, so nothing for the CSP to block
  - CSP drops fonts.googleapis.com and fonts.gstatic.com entirely
  - no third-party DNS + TLS handshake in the critical path
  - no visitor IPs handed to a third party on every page view

Run:  python scripts/fetch-fonts.py
Re-run only when a family, weight or subset changes; the output is committed.
"""

import re
import sys
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "public" / "fonts"

# A modern desktop UA is required: Google serves woff2 only to browsers it
# recognises, and older UA strings get ttf, which is roughly twice the bytes.
UA = (
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
    "(KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36"
)

# Only the subsets actually used. Pulling every subset Google offers would
# multiply the file count for scripts this site never renders.
FAMILIES = [
    ("Playfair Display", "wght@600;700;800;900", {"latin", "latin-ext"}),
    ("Inter", "wght@400;500;600;700", {"latin", "latin-ext"}),
    ("Noto Sans Telugu", "wght@400;500;600", {"telugu", "latin"}),
]


def fetch(url: str) -> bytes:
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(req, timeout=60) as r:
        return r.read()


def main() -> int:
    OUT.mkdir(parents=True, exist_ok=True)
    blocks: list[str] = []
    seen: set[str] = set()
    total = 0

    for family, axis, subsets in FAMILIES:
        css_url = (
            "https://fonts.googleapis.com/css2?family="
            + family.replace(" ", "+")
            + ":"
            + axis
            + "&display=swap"
        )
        css = fetch(css_url).decode("utf-8")

        # Google emits one @font-face per (weight, subset), each preceded by a
        # /* subset */ comment. That comment is the only place the subset name
        # appears, so it has to be tracked while walking the file in order.
        subset = None
        for chunk in re.split(r"(/\*\s*[\w\-\[\]]+\s*\*/)", css):
            m = re.fullmatch(r"/\*\s*([\w\-\[\]]+)\s*\*/", chunk.strip())
            if m:
                subset = m.group(1)
                continue
            if "@font-face" not in chunk or subset not in subsets:
                continue

            for face in re.findall(r"@font-face\s*\{[^}]*\}", chunk):
                weight = re.search(r"font-weight:\s*(\d+)", face).group(1)
                style = re.search(r"font-style:\s*(\w+)", face).group(1)
                url = re.search(r"url\((https://[^)]+\.woff2)\)", face).group(1)
                rng = re.search(r"unicode-range:\s*([^;]+);", face)

                slug = family.lower().replace(" ", "-")
                name = f"{slug}-{weight}-{subset}.woff2"
                if name in seen:
                    continue
                seen.add(name)

                data = fetch(url)
                (OUT / name).write_bytes(data)
                total += len(data)

                lines = [
                    "@font-face {",
                    f"  font-family: '{family}';",
                    f"  font-style: {style};",
                    f"  font-weight: {weight};",
                    # swap: render in the fallback immediately and repaint when
                    # the file lands. The alternative, `block`, leaves headings
                    # invisible for up to 3s on a slow connection.
                    "  font-display: swap;",
                    f"  src: url('/fonts/{name}') format('woff2');",
                ]
                if rng:
                    lines.append(f"  unicode-range: {rng.group(1).strip()};")
                lines.append("}")
                blocks.append("\n".join(lines))
                print(f"  {name:44s} {len(data) / 1024:6.1f} KB")

    if not blocks:
        print("No @font-face blocks produced — Google's CSS format changed.", file=sys.stderr)
        return 1

    header = (
        "/*\n"
        " * GENERATED by scripts/fetch-fonts.py — do not edit by hand.\n"
        " *\n"
        " * Self-hosted so the production CSP can stay strict. The previous\n"
        " * Google Fonts <link> relied on an inline onload handler, which\n"
        " * `script-src 'self'` blocked, leaving every webfont un-applied.\n"
        " */\n\n"
    )
    (OUT / "fonts.css").write_text(header + "\n\n".join(blocks) + "\n", encoding="utf-8")

    print(f"\n{len(blocks)} faces, {total / 1024:.0f} KB total -> public/fonts/")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
